from __future__ import annotations

from app.domains.agent_runs.tools.spec_models import AgentRuntimeToolSpec, ToolCatalogReferences

CHAPTER_WRITING_TOOL_SPECS: tuple[AgentRuntimeToolSpec, ...] = (
    AgentRuntimeToolSpec(
        name="chapter.brief",
        description="从可信项目上下文生成待作者确认的结构化 Chapter Brief。",
        domain="chapter",
        input_schema={},
        output_schema={},
        allowed_roles=("root_agent",),
        risk_level="write_pending",
        retry_safe=False,
        idempotent=False,
        execution_mode="sync",
        artifact_kinds=("chapter_brief",),
        required_capabilities=("llm",),
        evidence_fields=("brief_id", "revision", "context_provenance"),
        references=ToolCatalogReferences(workflow_nodes=("agent_runtime.chapter_brief",)),
    ),
    AgentRuntimeToolSpec(
        name="chapter.draft",
        description="按已确认 Chapter Brief 起草正文，不写项目文件。",
        domain="chapter",
        input_schema={},
        output_schema={},
        allowed_roles=("root_agent",),
        risk_level="write_pending",
        retry_safe=False,
        idempotent=False,
        execution_mode="sync",
        required_capabilities=("llm",),
        evidence_fields=("content_chars", "model", "brief_id"),
        references=ToolCatalogReferences(workflow_nodes=("agent_runtime.chapter_draft",)),
    ),
    AgentRuntimeToolSpec(
        name="chapter.check",
        description="按 Chapter Brief 检查草稿，区分硬失败与 advisory。",
        domain="chapter",
        input_schema={},
        output_schema={},
        allowed_roles=("root_agent",),
        risk_level="analyze",
        retry_safe=False,
        idempotent=False,
        execution_mode="sync",
        artifact_kinds=("chapter_check",),
        required_capabilities=("llm",),
        evidence_fields=("status", "hard_failure_count", "advisory_count"),
        references=ToolCatalogReferences(workflow_nodes=("agent_runtime.chapter_check",)),
    ),
    AgentRuntimeToolSpec(
        name="chapter.repair",
        description="针对 Chapter Brief 硬失败定向修复一次草稿，不写项目文件。",
        domain="chapter",
        input_schema={},
        output_schema={},
        allowed_roles=("root_agent",),
        risk_level="write_pending",
        retry_safe=False,
        idempotent=False,
        execution_mode="sync",
        required_capabilities=("llm",),
        evidence_fields=("content_chars", "brief_id"),
        references=ToolCatalogReferences(workflow_nodes=("agent_runtime.chapter_repair",)),
    ),
)
